name: OSSRH Repository Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:

    environment: deployment
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2.1.0
      with:
        java-version: 8
        distribution: 'adopt'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: GPG_PRIVATE_KEY
        gpg-passphrase: GPG_PASSPHRASE
    - name: Set up GPG
      run: |
         echo $GPG_PRIVATE_KEY | base64 --decode | gpg --import
         echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
    - name: Deploy
      run: mvn deploy -B -P deployment,config,site,deployment-release-pom,deployment-ossrh
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
